### ISSUE TITLE
Add readme section about polymer build dependencies

### ISSUE THREAD

**Issue by morbidick** [Protoss78/country-select#4]
For a default polymer build the data json files aren't included. They need to be explicitly mentioned in the polymer.json

```json
  "extraDependencies": [
    "bower_components/country-list/data/**/*.json"
  ]
```

If you'ld like ill write a PR in the next few days.

**Comment by Protoss78** [comment]
Thanks for notifying me about that. A PR is welcome any time. :+1:

**Comment by yairopro** [comment]
@morbidick [Like this](https://github.com/Protoss78/country-select/compare/master...yairopro:polymer-build?diff=unified&name=polymer-build#diff-2d9e645fa178242a8fe6ccfbeafe0d20)?

**Comment by morbidick** [comment]
@yairopro You need to define it in your app level polymer.json (polymer bundler doesnt read the component files). So best we can do is to add a readme section.

**Comment by yairopro** [comment]
@morbidick AAAAAAH...! Thanks a lot!

**Comment by Protoss78** [comment]
PR merged. Issue closed. Thanks for the contribution guys.
